spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-persistence
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      file: ./docker/compose.yml
      lifecycle-management: start_and_stop